import redis
import os

REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.environ.get('REDIS_PORT')
print("Connecting to redis....")
r = redis.Redis(host=REDIS_HOST, port=REDIS_PORT, db=0)
r.set('foo1', 'bar1')
r.set('foo2', 'bar2')
r.set('foo3', 'bar3')
r.set('foo4', 'bar4')
r.set('foo5', 'bar5')
r.set('foo6', 'bar6')
r.set('foo7', 'bar7')
r.set('foo8', 'bar8')
r.set('foo9', 'bar9')
r.set('foo10', 'bar10')
print(r.get('foo1'))
print(r.get('foo2'))
print(r.get('foo3'))
print(r.get('foo4'))
print(r.get('foo5'))
print(r.get('foo6'))
print(r.get('foo7'))

